{{--
    Meta Pixel base code — storefront shells only (never admin/vendor/maintenance).
    Generated by us from validated numeric IDs; no admin/vendor HTML is ever output.
    Every event uses trackSingle so each pixel only gets its own events.
--}}
@if(\App\Support\MetaPixel::active())
@php $mpPlatform = \App\Support\MetaPixel::platformIds(); $mpOwn = \App\Support\MetaPixel::platformScopeOwn(); @endphp
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
(function (ids, own) {
    try {
        ids.forEach(function (id) {
            // Scope 'own': Meta's automatic events could pick up vendor products — keep them off.
            if (own) fbq('set', 'autoConfig', false, id);
            fbq('init', id);
            fbq('trackSingle', id, 'PageView');
        });
    } catch (e) {}
})(@json($mpPlatform), @json($mpOwn));
</script>
@endif
